# Generated by Django 3.2 on 2021-05-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_company_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='id',
            new_name='job_id',
        ),
    ]
