# Generated by Django 3.2 on 2021-05-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210507_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cdescription',
            field=models.TextField(default='Description: ', help_text='Add Company Description', max_length=2000),
        ),
    ]
