# Generated by Django 3.2 on 2021-05-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_company_cdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='job',
        ),
    ]
